version: "3.7"

services:
  image-previewer:
    image: "image-previewer-img"
    build: .
    environment:
      HTTP_PORT: 8080
      CACHE_MAX_ELEM_CNT: 50
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - image-previewer
    volumes:
      - "./testdata/images:/usr/share/nginx/html/images"
